version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql-container
    environment:
      DB_USER: root
      DB_ROOT_PASSWORD: password
      DB_DATABASE: votes
      DB_HOST: mysql-container
    networks:
      - my_network

  mysql-container:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: votes
    networks:
      - my_network

networks:
  my_network:
